future: true
permalink: /:title/
url: http://muhaokang.github.io
name: Haokang Mu
author: Haokang Mu
email: hkmu9248@gmail.com
duoshuo: Haokang Mu
beian: 
cnzz: 
weibo: Haokang Mu
github: muhaokang
paginate: 20
highlighter: rouge
truncate: true
about: "Haokang Mu"
